# Force fields
# Please, put an asterisk front of the force field name for the energy calculation
#  and use $ symbol in front of the force field name for the coordination number calculation.
# You can choose following force fields:
# MM3. MMFF, OPLSAA, OPLSAALIGPARGEN, AMOEBA09, SMOOTHAA
# Please, be aware You can't use MM3 force field parameters for the coordination number calculation.
# Please, keep in mind that if You choose OPLSAALIGPARGEN and set conformational analysis at same time
#  MIPET will use same parameter set from LigParGen but the new optimized structure needs new
#  parameter set. 
# -------------------------
* OPLSAALIGPARGEN
$ 

#--------------------------
# Test particles
#--------------------------
#H2O
#Me
#MeOH
#Et
#Me2O

# -------------------------
# Particles
# -------------------------
AcCO
AcNH2
Bu
CisButene
DiMeNH
DMP
Et
Et2O
Ethene
EtNH2
EtOH
Et2O
Furan
Guanidine
H2O
HAc
HCHO
Imidazole
Me
Me2O
Me2S
Me2S2
MeAc
MeAcNH
MeNH2
MeOH
MeSH
MP
Ph
PhNH2
PhOH
Pr
PrImine
PrOH
Pyridine
Pyrrole
TriMeN