#/**
# * MIPET - Mesoscopic Interaction Parameter Estimation with Tinker
# * Copyright (C) 2024  Achim Zielesny (achim.zielesny@googlemail.com)
# * 
# * Source code is available at <https://github.com/zielesny/MIPET>
# * 
# * This program is free software: you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation, either version 3 of the License, or
# * (at your option) any later version.
# * 
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# * 
# * You should have received a copy of the GNU General Public License
# * along with this program.  If not, see <http://www.gnu.org/licenses/>.
# */

# Force fields
# Please, put an asterisk front of the force field name for the energy calculation
#  and use $ symbol in front of the force field name for the coordination number calculation.
# You can choose following force fields:
# MM3. MMFF, OPLSAA, OPLSAALIGPARGEN, AMOEBA09, SMOOTHAA
# Please, be aware You can't use MM3 force field parameters for the coordination number calculation.
# Please, keep in mind that if You choose OPLSAALIGPARGEN and set conformational analysis at same time
#  MIPET will use same parameter set from LigParGen but the new optimized structure needs new
#  parameter set. 
# -------------------------
* OPLSAALIGPARGEN
$ 

#--------------------------
# Test particles
#--------------------------
H2O
#Me
MeOH
#Et
#Me2O

# -------------------------
# Particles
# -------------------------
#AcNH2
#Bu
#CisButene
#DMP
#Et
#Et2O
#Ethene
#EtNH2
#EtOH
#Et2O
#Furan
#Guanidine
#H2O
#HAc
#HCHO
#Imidazole
#Me
#Me2CO
#Me2NH
#Me2O
#Me2S
#Me2S2
#Me3N
#MeAc
#MeAcNH
#MeNH2
#MeOH
#MeSH
#MP
#Ph
#PhNH2
#PhOH
#Pr
#PrImine
#Pyridine
#Pyrrole
