# Force fields
# Please, put an asterisk front of the force field name for the energy calculation
#  and use $ symbol in front of the force field name for the coordination number calculation.
# Please be aware You can't use MM3 force field parameters for the coordination number calculation.
# -------------------------
* OPLSAA
$

#--------------------------
# Test particles
#--------------------------
#H2O
#Me
MeOH
Et
#Me2O

# -------------------------
# Particles
# -------------------------
#AcCO
#AcNH2
#Azolid
#Bu
#CisButene
#DiMeNH
#DMP
#DMP2
#Et
#Ethene
#Ethyne
#EtNH2
#EtOH
#Et2O
#Furan
#Guanidine1
#Guanidine2
#HAc
#HCHO
#H2O
#Imidazole
#Me
#MeAc
#MeAcNH
#MeNH2
#MeOH
#MeSH
#Me2O
#Me2S
#Me2S2
#MP
#MP2
#Ph
#PhNH2
#PhOH
#Pr
#Prlmine1
#Prlmine2
#PrOH
#Pyridine
#Pyrrole
#TriMeN